# Generated by Django 4.1.3 on 2022-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
