# Generated by Django 4.1.3 on 2022-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alien_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
